[package]
name = "photonix"
version = "0.1.1"
authors = ["bsoptei <bsoptei@gmail.com>"]
description = "Solutions for functional optics."
license = "MIT"
edition = "2018"
repository = "https://github.com/bsoptei/photonix"

[dependencies]
photonix_derive = "0.1.1"